### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by patrikarlos** [raghuvinayak/anm#1]
I'm running in console, I cant read a docx file in console. Please keep the readme as pure ASCII.
After a long and difficult journey; I started with a clean Ubuntu 16.04LTS, and I don not have the /home/user/consumer-bitrate folder? how/where do I get that?

**Comment by patrikarlos** [comment]
You also missed the expect package.

**Comment by patrikarlos** [comment]
I've tried to launch the api,py, it starts but when I try to add streams I get errors.
[request: curl http://194.47.151.90:5000/run/enp0s8_010000000040_010000000045]

console from consumer;
 python api.py 
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
194.47.133.183 - - [12/Sep/2017 10:25:05] "GET /run/enp0s8_010000000040_010000000045 HTTP/1.1" 200 -
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'str' object is not callable

**Comment by raghuvinayak** [comment]
You can get it from her https://github.com/DPMI/consumer-bitrate

**Comment by patrikarlos** [comment]
That gives me a consumer-bitrate binary. Why would I have to place it in /home/user
Point is that the doc. is wrong.

**Comment by raghuvinayak** [comment]
Can you give us an appointment so that i can explain you clearly

On 4 Oct 2017 1:49 pm, "Patrik Arlos" <notifications@github.com> wrote:

That gives me a consumer-bitrate binary. Why would I have to place it in
/home/user
Point is that the doc. is wrong.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/raghuvinayak/anm/issues/1#issuecomment-334130750>, or mute
the thread

**Comment by patrikarlos** [comment]
At this point; correct the documentation so that by reading and following it ends up with a the solution that works.

**Comment by raghuvinayak** [comment]
No i just put the python api file in consumer bitrate folder and as i
mention in readme file for better understanding

**Comment by patrikarlos** [comment]
update the document. I'll follow it line by line.

**Comment by raghuvinayak** [comment]
Ok patrik i will update it

**Comment by raghuvinayak** [comment]
Hey Patrik,
I have updated Readme file. Please check this.

Regards
Raghu
Starks group.

**Comment by raghuvinayak** [comment]
i have updated and issue has been solved
